-- 2026-04-24
-- 修复通用公共字段注释，避免通过临时迁移改名后丢失列注释。

ALTER TABLE `department`
    MODIFY COLUMN `created_by_user_id` BIGINT DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `created_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    MODIFY COLUMN `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `updated_by_user_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    MODIFY COLUMN `updated_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    MODIFY COLUMN `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN `enabled_flag` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除';

ALTER TABLE `user`
    MODIFY COLUMN `created_by_user_id` BIGINT DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `created_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    MODIFY COLUMN `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `updated_by_user_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    MODIFY COLUMN `updated_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    MODIFY COLUMN `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN `enabled_flag` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除';

ALTER TABLE `attendance_rule`
    MODIFY COLUMN `created_by_user_id` BIGINT DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `created_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    MODIFY COLUMN `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `updated_by_user_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    MODIFY COLUMN `updated_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    MODIFY COLUMN `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN `enabled_flag` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除';

ALTER TABLE `attendance_record`
    MODIFY COLUMN `created_by_user_id` BIGINT DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `created_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    MODIFY COLUMN `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `updated_by_user_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    MODIFY COLUMN `updated_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    MODIFY COLUMN `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN `enabled_flag` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除';

ALTER TABLE `leave_application`
    MODIFY COLUMN `created_by_user_id` BIGINT DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `created_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    MODIFY COLUMN `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `updated_by_user_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    MODIFY COLUMN `updated_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    MODIFY COLUMN `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN `enabled_flag` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除';

ALTER TABLE `makeup_application`
    MODIFY COLUMN `created_by_user_id` BIGINT DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `created_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
    MODIFY COLUMN `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `updated_by_user_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    MODIFY COLUMN `updated_by_user_name` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    MODIFY COLUMN `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN `enabled_flag` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN `deleted_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除';
